### ISSUE TITLE
When an assertion fails in the test the remaining steps are not executed

### ISSUE THREAD

**Issue by paulmccormack** [ptrthomas/karate-gatling-demo#3]
Hi Peter

I am loving working with your framework and decided to try out the performance test feature.

I was running a performance test using karate/gatling based on the example project you have and i noticed that when an assertion fails the remaining steps in the scenario are not executed.

To confirm it wasn't an issue with my setup I ran your demo cats performance test and can see the same behaviour.  The steps after the assertion are failing.  If I remove the failing assertion then all steps run in your demo project.

Also another question - in the setup if you define 2 profiles to run (like your create and delete) do they run sequentially or concurrent.

Cheers

Paul

**Comment by ptrthomas** [comment]
> when an assertion fails the remaining steps in the scenario are not executed.

I think this is the right behavior. feel free to raise a feature request on the main project for perhaps a flag to change this.

> run sequentially or concurrent.

concurrent
