### ISSUE TITLE
Failed to execute goal

### ISSUE THREAD

**Issue by viperx77** [ptrthomas/karate-gatling-demo#4]
```
git clone https://github.com/ptrthomas/karate-gatling-demo.git
mvn clean test-compile gatling:test
```

`[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.2.4:test (default-cli) on project karate-gatling-demo: Gatling failed.: Simulations compilation failed. Process exited with an error: 1`

I tried updating plug-ins but it still did not work. 

I'm a gatling newbie and just was just hoping to see this work to explore further.

**Comment by ptrthomas** [comment]
@viperx77 I'm guessing you tried to run on java 9 or 11 - because the gatling integration works only on 8.

but this has been fixed, if you can build from source, please refer this ticket and try please: https://github.com/intuit/karate/issues/647

**Comment by viperx77** [comment]
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by ptrthomas** [comment]
@viperx77 then all I can think of is this: 
https://github.com/intuit/karate/issues/404#issuecomment-417630286

closing as cannot replicate.
