### ISSUE TITLE
Karate Gatling tests fails with error: io.gatling.compiler.ZincCompiler

### ISSUE THREAD

**Issue by guptapranay** [ptrthomas/karate-gatling-demo#5]
[karate-demo.zip](https://github.com/ptrthomas/karate-gatling-demo/files/3898628/karate-demo.zip)
Hi @ptrthomas ,
I am facing issues running feature file with Gatling. I am sure, I am doing something silly or missing an important point. I would like your help in knowing, where I am making mistake. I am attaching zip of the project. 

Apologize for the trouble.

Error:
`20:04:17.204 [main] ERROR io.gatling.compiler.ZincCompiler$ - /Users/pranaytgupta/Documents/LBG/JavaProjects/karate-demo/src/test/java/employeeDetails/EmployeeDetailsTestSimulation.scala:4:24: object PreDef is not a member of package io.gatling.core
import io.gatling.core.PreDef._
                       ^
20:04:17.207 [main] ERROR io.gatling.compiler.ZincCompiler$ - /Users/pranaytgupta/Documents/LBG/JavaProjects/karate-demo/src/test/java/employeeDetails/EmployeeDetailsT
[karate-demo.zip](https://github.com/ptrthomas/karate-gatling-demo/files/3898627/karate-demo.zip)
estSimulation.scala:5:24: object PreDef is not a member of package io.gatling.core
import io.gatling.core.PreDef.Simulation`

**Comment by ptrthomas** [comment]
@guptapranay sorry you have to follow the instructions here to the letter: https://github.com/intuit/karate/wiki/How-to-Submit-an-Issue

your project is NOT a minimal complete verifiable example there is extra stuff in your `pom.xml`

anyway, some hints:

you have a typo `<include>employeeDetails.EmployeeDetailsTestSimulation</include>`
please use  Karate 0.9.5.RC4
remove the gatling stuff in your `pom.xml`

so please try again and use the main karate project for issues. this repo is being deprecated
